### ISSUE TITLE
to answer couple of notes in the schema file

### ISSUE THREAD

**Issue by bsr203** [xymostech/relay-google-datastore-test#1]
Hi Emily,

just raising this issue as I saw couple of notes in the schema file about why each node need a cursor, and also about viewer. Hope below two thread help to answer them.

https://github.com/facebook/relay/issues/112
https://github.com/graphql/graphql-relay-js/issues/27

I appreciate your work and open sourcing this project. It is helping me to understand how to hookup relay to a scalable backend like GAE.

thanks.
bsr

**Comment by bsr203** [comment]
I will keep it open to make sure you see this :-)

**Comment by xymostech** [comment]
@bsr203 Thanks for the information! I think I found the explanation of viewer after I wrote that, and had sorta guessed about the cursor stuff but wasn't entirely sure. Thanks for the info! I haven't figured out how to add cursors to elements that work well with the GAE cursors we get from querying the GAE datastore, maybe looking through some of the integrations with other databases will help.

**Comment by bsr203** [comment]
Hi.. I never worked with nodejs GAE, but did pagination with GAE go (golang) runtime once. I may look into it once I need it, but your project was a good start to learn from. thanks.
